[build]
builder = "nixpacks"
watchPatterns = ["backend/**/*"]
nixpacksConfigPath = "backend"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
numReplicas = 1
healthcheckPath = "/healthcheck"
healthcheckTimeout = 100

[deploy.env]
PORT = "1337"
HOST = "0.0.0.0"
