[build]
builder = "nixpacks"
watchPatterns = ["backend/**/*"]
nixpacksConfigPath = "backend"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]
cmds = ["npm config set legacy-peer-deps true"]

[phases.install]
cmds = ["npm install --production=false"]

[phases.build]
cmds = ["npm run build", "npm run strapi import -- --file export.tar.gz.tar.gz.enc --key YOUR_ENCRYPTION_KEY"]

[start]
cmd = "npm run start"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
numReplicas = 1
healthcheckPath = "/healthcheck"
healthcheckTimeout = 100

[deploy.env]
PORT = "1337"
HOST = "0.0.0.0"
NODE_ENV = "production"
